import React from 'react';
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { 
  nabhTaskAutoGenerator, 
  NABH_TASK_TEMPLATES, 
  NabhTaskCadence 
} from '../lib/data/nabhTaskAutoGenerator';
import { nabhReadinessStore } from '../lib/mocks/nabhReadinessStore';
import { workItemStore } from '../lib/mocks/workItemMock';
import { NabhTaskAutoGeneratorModal } from '../components/organization/NabhTaskAutoGeneratorModal';
import { AuthProvider } from '../lib/auth/AuthContext';
import ExecutionPage from '../app/(app)/execution/page';
import { StavyaQualityCommandCentre } from '../components/organization/NabhCommandCentreView';

// Mock next/navigation
vi.mock('next/navigation', () => ({
  useRouter: () => ({
    push: vi.fn(),
    replace: vi.fn(),
    prefetch: vi.fn(),
  }),
  useSearchParams: () => new URLSearchParams(),
  usePathname: () => '/execution',
}));

describe('NABH 6th Edition Task Auto-Generation Engine & UI Suite', () => {
  beforeEach(() => {
    workItemStore.resetData();
    nabhReadinessStore.resetData();
  });

  describe('1. Task Auto-Generator Rules & Recurrence Cadences', () => {
    it('contains comprehensive task templates across all 10 NABH 6th Edition chapters', () => {
      const templates = nabhTaskAutoGenerator.getTemplates();
      expect(templates.length).toBeGreaterThanOrEqual(25);

      const uniqueChapters = Array.from(new Set(templates.map(t => t.chapter)));
      expect(uniqueChapters).toHaveLength(10);
      expect(uniqueChapters).toEqual(
        expect.arrayContaining(['AAC', 'COP', 'MOM', 'PRE', 'IPC', 'PSQ', 'ROM', 'FMS', 'HRM', 'IMS'])
      );
    });

    it('covers all standard recurrence cadences (Daily, Weekly, Monthly, Quarterly, Annual)', () => {
      const stats = nabhTaskAutoGenerator.getStats();
      expect(stats.byCadence.DAILY).toBeGreaterThan(0);
      expect(stats.byCadence.WEEKLY).toBeGreaterThan(0);
      expect(stats.byCadence.MONTHLY).toBeGreaterThan(0);
      expect(stats.byCadence.QUARTERLY).toBeGreaterThan(0);
      expect(stats.byCadence.ANNUAL).toBeGreaterThan(0);
      expect(stats.statutoryCount).toBeGreaterThan(15);
    });

    it('generates tasks for specific chapters when filtered', () => {
      const copTasks = nabhTaskAutoGenerator.generateTasks({ targetChapters: ['COP'] });
      expect(copTasks.length).toBeGreaterThanOrEqual(3);
      expect(copTasks.every(t => t.tags?.includes('CHAPTER_COP'))).toBe(true);

      const ipcTasks = nabhTaskAutoGenerator.generateTasks({ targetChapters: ['IPC'] });
      expect(ipcTasks.length).toBeGreaterThanOrEqual(3);
      expect(ipcTasks.every(t => t.tags?.includes('CHAPTER_IPC'))).toBe(true);
    });

    it('generates tasks for specific cadences when filtered', () => {
      const dailyTasks = nabhTaskAutoGenerator.generateTasks({ targetCadences: ['DAILY'] });
      expect(dailyTasks.length).toBeGreaterThan(0);
      expect(dailyTasks.every(t => t.tags?.includes('CADENCE_DAILY'))).toBe(true);

      const monthlyTasks = nabhTaskAutoGenerator.generateTasks({ targetCadences: ['MONTHLY'] });
      expect(monthlyTasks.length).toBeGreaterThan(0);
      expect(monthlyTasks.every(t => t.tags?.includes('CADENCE_MONTHLY'))).toBe(true);
    });
  });

  describe('2. RACI Governance & Execution Deliverable Contracts (EDC)', () => {
    it('strictly assigns Responsible Chapter Champion and Accountable Authority to every autogenerated task', () => {
      const allGenerated = nabhTaskAutoGenerator.generateTasks({ cycleName: 'Q3 2026 Audit' });
      
      allGenerated.forEach(task => {
        // RACI verification
        expect(task.raci).toBeDefined();
        expect(task.raci?.responsible_id).toBeTruthy();
        expect(task.raci?.responsible_name).toBeTruthy();
        expect(task.raci?.accountable_id).toBeTruthy();
        expect(task.raci?.accountable_name).toBeTruthy();
        expect(task.raci?.consulted_names?.length).toBeGreaterThan(0);
        expect(task.raci?.informed_names?.length).toBeGreaterThan(0);

        // Accountable routing rule
        if (task.tags?.includes('CHAPTER_ROM')) {
          expect(task.raci?.accountable_id).toBe('e071'); // MD Dr. Mirant Dave
        } else {
          expect(task.raci?.accountable_id).toBe('e069'); // Director Quality Dr. Akruti Dave
        }
      });
    });

    it('attaches comprehensive Execution Deliverable Contracts (EDC) to every autogenerated task', () => {
      const allGenerated = nabhTaskAutoGenerator.generateTasks();

      allGenerated.forEach(task => {
        expect(task.edc).toBeDefined();
        expect(task.edc?.expected_outcome).toBeTruthy();
        expect(task.edc?.definition_of_done).toBeTruthy();
        expect(task.edc?.evidence_required).toBeTruthy();
        expect(task.edc?.completion_criteria?.length).toBeGreaterThan(0);
      });
    });
  });

  describe('3. Store Integration & Reactive Work Queue Synchronization', () => {
    it('automatically triggers task generation upon store initialization', () => {
      const autogenerated = nabhReadinessStore.getAutogeneratedWorkItems();
      expect(autogenerated.length).toBeGreaterThanOrEqual(25);
    });

    it('injects new tasks into workItemStore when triggerAutoGeneration is called', () => {
      const initialCount = workItemStore.getWorkItems().length;
      
      // Trigger cycle generation
      const created = nabhReadinessStore.triggerAutoGeneration({
        cycleName: 'Special Audit Oct 2026',
        targetChapters: ['AAC', 'MOM'],
      });

      expect(created.length).toBeGreaterThanOrEqual(0); // If already generated, won't duplicate
      const allItems = workItemStore.getWorkItems();
      expect(allItems.length).toBeGreaterThanOrEqual(initialCount);
    });
  });

  describe('4. Interactive UI Components & Auto-Generator Modal', () => {
    it('renders NabhTaskAutoGeneratorModal with stats, filters, and preview templates', () => {
      const handleClose = vi.fn();
      const handleGenerated = vi.fn();

      render(
        <NabhTaskAutoGeneratorModal
          isOpen={true}
          onClose={handleClose}
          onTasksGenerated={handleGenerated}
        />
      );

      expect(screen.getByText(/Autonomous NABH Task Auto-Generator/i)).toBeDefined();
      expect(screen.getByText(/Daily Routines/i)).toBeDefined();
      expect(screen.getByText(/Weekly Audits/i)).toBeDefined();
      expect(screen.getByText(/Monthly Submissions/i)).toBeDefined();

      // Filter by cadence
      const dailyBtn = screen.getByRole('button', { name: 'DAILY' });
      fireEvent.click(dailyBtn);

      // Run generation
      const runBtn = screen.getByRole('button', { name: /Run Auto-Generation Engine/i });
      fireEvent.click(runBtn);
    });

    it('renders Auto-Generate NABH Tasks button on Execution Page and filters autogenerated tasks', async () => {
      render(
        <AuthProvider>
          <ExecutionPage />
        </AuthProvider>
      );

      // Verify top action button exists
      const autoGenBtn = await screen.findByRole('button', { name: /Auto-Generate NABH Tasks/i });
      expect(autoGenBtn).toBeDefined();

      // Verify filter pill exists
      const nabhPill = await screen.findByRole('button', { name: /NABH Autogenerated/i });
      expect(nabhPill).toBeDefined();

      // Click filter pill
      fireEvent.click(nabhPill);
    });
  });
});
