"""Declarative base, naming convention and shared column mixins.

DATABASE.md §1 conventions implemented here:

* UUID primary keys.
* ``created_at`` / ``updated_at`` as UTC ``timestamptz``.
* Lowercase snake_case names, plural table names.
* Optimistic concurrency ``version`` on frequently edited aggregates.

The explicit naming convention makes Alembic autogenerate deterministic: index
and constraint names are derived, never database-assigned, so a regenerated
migration produces the same DDL.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import MetaData, Uuid, func
from sqlalchemy.dialects.postgresql import TIMESTAMP
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)

#: Reusable column type for UUID primary/foreign keys.
UUID_PK = Uuid(as_uuid=True)

#: Reusable column type for UTC instants.
UTC_TIMESTAMP = TIMESTAMP(timezone=True)


class Base(DeclarativeBase):
    """Declarative base for every LAKSHYA table."""

    metadata = metadata

    def __repr__(self) -> str:  # pragma: no cover - diagnostics only
        identifier = getattr(self, "id", None)
        return f"<{type(self).__name__} id={identifier}>"


def uuid_pk() -> Mapped[uuid.UUID]:
    """UUID primary key generated by the application (DATABASE.md §1)."""
    return mapped_column(UUID_PK, primary_key=True, default=uuid.uuid4)


def uuid_fk(target: str, *, nullable: bool = False, ondelete: str | None = None) -> Any:
    """UUID foreign key column with a real database-level constraint."""
    from sqlalchemy import ForeignKey

    return mapped_column(
        UUID_PK,
        ForeignKey(target, ondelete=ondelete),
        nullable=nullable,
    )


class TimestampMixin:
    """UTC creation and update timestamps.

    ``server_default`` / ``onupdate`` keep the values correct even for writes
    that bypass the ORM (data migrations, maintenance SQL).
    """

    created_at: Mapped[datetime] = mapped_column(
        UTC_TIMESTAMP, nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        UTC_TIMESTAMP, nullable=False, server_default=func.now(), onupdate=func.now()
    )


class VersionMixin:
    """Optimistic concurrency counter for editable aggregates.

    Surfaced to clients as the resource ``ETag``. Update commands take a row
    lock (``SELECT ... FOR UPDATE``), compare the caller's ``If-Match`` against
    this value and increment it, so a stale write returns ``412`` instead of
    silently overwriting a concurrent change (API.md §1).

    The counter is managed explicitly in the service layer rather than through
    SQLAlchemy's ``version_id_col``, so that the version check, the audit event
    and the row lock all live in one readable place.
    """

    version: Mapped[int] = mapped_column(nullable=False, default=1, server_default="1")
