import { NABH_6TH_EDITION_CHECKLIST_ITEMS, NABH_6TH_EDITION_CHAMPIONS, NabhChecklistItem, NabhChapterChampionProfile } from '../data/nabhReadinessChecklistData';
import { nabhTaskAutoGenerator, NabhAutoGenerationOptions, NabhTaskTemplate, NabhGenerationStats } from '../data/nabhTaskAutoGenerator';
import { workItemStore } from './workItemMock';
import { WorkItem, WorkItemPriority, WorkItemStatus } from '../../types/workItem';

class NabhReadinessStore {
  private checklist: NabhChecklistItem[] = [];
  private champions: NabhChapterChampionProfile[] = [];
  private isInitialized = false;

  constructor() {
    this.init();
  }

  private init() {
    this.checklist = [...NABH_6TH_EDITION_CHECKLIST_ITEMS];
    this.champions = [...NABH_6TH_EDITION_CHAMPIONS];
    this.syncChecklistToWorkItems();
    this.triggerAutoGeneration({ cycleName: 'Initial Cycle' });
    this.isInitialized = true;
  }

  public resetData() {
    this.checklist = [...NABH_6TH_EDITION_CHECKLIST_ITEMS];
    this.champions = [...NABH_6TH_EDITION_CHAMPIONS];
    this.syncChecklistToWorkItems();
    this.triggerAutoGeneration({ cycleName: 'Current Active Cycle' });
  }

  /**
   * Synchronize all NABH 6th Edition Champion checklist items into the central workItemStore as active To-Dos
   */
  public syncChecklistToWorkItems() {
    const existingWorkItems = workItemStore.getWorkItems();
    const existingIds = new Set(existingWorkItems.map(w => w.id));

    this.checklist.forEach(item => {
      const workItemId = `wi-${item.id}`;
      if (!existingIds.has(workItemId)) {
        const priority: WorkItemPriority = item.weight >= 5 ? 'urgent' : item.weight >= 4 ? 'high' : 'medium';
        const status: WorkItemStatus = item.status === 'VERIFIED' ? 'completed' 
          : item.status === 'COMPLETED' ? 'in_progress' 
          : item.status === 'IN_PROGRESS' ? 'in_progress' 
          : 'todo';

        const workItem: WorkItem = {
          id: workItemId,
          organization_id: 'org-stavya-001',
          created_by: 'system-nabh-engine',
          version: 1,
          source_type: 'nabh_action',
          source_title: `NABH Chapter ${item.chapter}`,
          title: `[NABH-6th ${item.chapter}] ${item.title}`,
          description: `${item.description} (Evidence Required: ${item.evidenceRequired})`,
          department_id: `dept-${item.chapter.toLowerCase()}`,
          department_name: `NABH Chapter ${item.chapter}`,
          owner_id: item.championId,
          owner_name: item.championName,
          priority,
          status,
          progressPercent: item.status === 'VERIFIED' ? 100 : item.status === 'COMPLETED' ? 90 : item.status === 'IN_PROGRESS' ? 50 : 0,
          due_at: item.dueDate,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
          raci: {
            accountable_id: item.chapter === 'ROM' ? 'e001' : 'e069',
            accountable_name: item.chapter === 'ROM' ? 'Dr. Mirant Bharat Dave (MD)' : 'Dr. Akruti Mirant Dave (Director Quality)',
            responsible_id: item.championId,
            responsible_name: item.championName,
            consulted_names: [item.committeeName, item.coChampionName || 'Quality Team'],
            informed_names: ['Executive Governance Board', 'MD Office'],
          },
          tags: ['NABH_6TH_EDITION', `CHAPTER_${item.chapter}`, 'ACCREDITATION_TODO', 'CHAMPION_CHECKLIST'],
        };

        workItemStore.createWorkItem(workItem);
      }
    });
  }

  /**
   * Autonomous Task Auto-Generation:
   * Generates recurring statutory compliance, clinical audits, committee agendas, and quality indicator tasks
   * and automatically injects them into the active workItemStore.
   */
  public triggerAutoGeneration(options: NabhAutoGenerationOptions = {}): WorkItem[] {
    const generatedTasks = nabhTaskAutoGenerator.generateTasks(options);
    const existingWorkItems = workItemStore.getWorkItems();
    const existingTitles = new Set(existingWorkItems.map(w => w.title));

    const newlyCreated: WorkItem[] = [];

    generatedTasks.forEach(task => {
      // Avoid duplicate tasks with the exact same title if not forced
      if (!existingTitles.has(task.title)) {
        const created = workItemStore.createWorkItem(task, 'Autonomous NABH Engine');
        newlyCreated.push(created);
      }
    });

    return newlyCreated;
  }

  public getAutogeneratedWorkItems(): WorkItem[] {
    return workItemStore.getWorkItems().filter(w => w.tags?.includes('AUTOGENERATED'));
  }

  public getAutoGenerationStats(): NabhGenerationStats {
    return nabhTaskAutoGenerator.getStats();
  }

  public getChecklist(): NabhChecklistItem[] {
    return this.checklist;
  }

  public getChampions(): NabhChapterChampionProfile[] {
    return this.champions;
  }

  public getChapterItems(chapter: string): NabhChecklistItem[] {
    return this.checklist.filter(i => i.chapter.toUpperCase() === chapter.toUpperCase());
  }

  public getChampionItems(championId: string): NabhChecklistItem[] {
    return this.checklist.filter(i => i.championId === championId);
  }

  public updateItemStatus(itemId: string, status: NabhChecklistItem['status'], remarks?: string, verifiedBy?: string): NabhChecklistItem | null {
    const idx = this.checklist.findIndex(i => i.id === itemId);
    if (idx === -1) return null;

    const item = this.checklist[idx];
    const nowIso = new Date().toISOString();

    const updated: NabhChecklistItem = {
      ...item,
      status,
      remarks: remarks !== undefined ? remarks : item.remarks,
      verifiedAt: status === 'VERIFIED' ? nowIso : item.verifiedAt,
      verifiedBy: status === 'VERIFIED' ? (verifiedBy || 'Quality Directorate') : item.verifiedBy,
    };

    this.checklist[idx] = updated;

    // Sync to WorkItem store
    try {
      const workItemId = `wi-${item.id}`;
      const workStatus: WorkItemStatus = status === 'VERIFIED' ? 'completed' : status === 'COMPLETED' ? 'in_progress' : status === 'IN_PROGRESS' ? 'in_progress' : 'todo';
      const progress = status === 'VERIFIED' ? 100 : status === 'COMPLETED' ? 90 : status === 'IN_PROGRESS' ? 50 : 0;

      if (workItemStore.getWorkItem(workItemId)) {
        workItemStore.patchWorkItem(workItemId, {
          status: workStatus,
          progressPercent: progress,
          update_note: `NABH 6th Edition Checklist updated to ${status}. Remarks: ${remarks || 'Status updated by Chapter Champion.'}`,
        });
      }
    } catch (e) {
      console.warn('Could not sync checklist status to workItemStore', e);
    }

    return updated;
  }

  public getReadinessSummary() {
    const total = this.checklist.length;
    const verified = this.checklist.filter(i => i.status === 'VERIFIED').length;
    const completed = this.checklist.filter(i => i.status === 'COMPLETED').length;
    const inProgress = this.checklist.filter(i => i.status === 'IN_PROGRESS').length;
    const pending = this.checklist.filter(i => i.status === 'PENDING').length;

    // Weighted Score
    const totalWeight = this.checklist.reduce((acc, i) => acc + i.weight, 0);
    const achievedWeight = this.checklist.reduce((acc, i) => {
      if (i.status === 'VERIFIED') return acc + i.weight;
      if (i.status === 'COMPLETED') return acc + i.weight * 0.9;
      if (i.status === 'IN_PROGRESS') return acc + i.weight * 0.5;
      return acc;
    }, 0);

    const readinessPercent = totalWeight > 0 ? Math.round((achievedWeight / totalWeight) * 100) : 0;

    return {
      total,
      verified,
      completed,
      inProgress,
      pending,
      readinessPercent,
      chapterBreakdown: this.champions.map(c => {
        const items = this.getChapterItems(c.chapter);
        const chapVerified = items.filter(i => i.status === 'VERIFIED').length;
        const chapCompleted = items.filter(i => i.status === 'COMPLETED').length;
        const chapTotal = items.length;
        const chapPercent = chapTotal > 0 ? Math.round(((chapVerified + chapCompleted * 0.9) / chapTotal) * 100) : 0;
        return {
          chapter: c.chapter,
          chapterTitle: c.chapterTitle,
          championName: c.championName,
          total: chapTotal,
          verified: chapVerified,
          completed: chapCompleted,
          percent: chapPercent,
        };
      })
    };
  }
}

export const nabhReadinessStore = new NabhReadinessStore();
